# Setup
title:               OPEN DATA HANDBOOK
tagline:             'California Health and Human Services Agency'
description:         'CHHS Open Data Handbook'
url:                 http://chhsdata.github.io/opendatahandbook
baseurl:             'chhsdata.github.io/opendatahandbook/'
paginate:            5

# About/contact
author:
  name:              California Health and Human Services Agency
  url:               https://twitter.com/chhsagency
  email:             opendata@chhs.ca.gov

# Custom vars
version:             1.0 | January 2015
github:
  repo:              https://github.com/chhsdata/opendatahandbook
