# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               OPEN DATA HANDBOOK
tagline:             'California Health and Human Services Agency'
description:         'CHHS Open Data Handbook'
url:                 http://chhsopendata.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              California Health and Human Services Agency
  url:               https://twitter.com/chhsagency
  email:             opendata@chhs.ca.gov

# Custom vars
version:             3.0 | January 2015
github:
  repo:              https://github.com/chhsopendata/chhsopendata.github.io
